Django/secondProject/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

Django/secondProject/secondProject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('tasks/',include('tasks.urls'))
]

Django/secondProject/tasks/urls.py
from django.urls import path 
from . import views 

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
]

Django/secondProject/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return HttpResponse('Hello Django')

Django/secondProject/tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms 
from django.urls import reverse 



class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = {}
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index")) 
        else:
            return render(request, "tasks/add.html", {
                "form":form
            })
    return render(request, "tasks/add.html", {
        'form':NewTaskForm()
    })

Django/secondProject/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1>add task </h1>
        <form action="{% url 'tasks:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <br>
        <a href="{% url 'tasks:index' %}">back</a>
{% endblock %}

Django/secondProject/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
        <h1> tasks </h1>
        <ul>
            {% for task in tasks %}
                 <li>{{ task }}</li>
            {% empty %}
                 <li> no task </li>
            {% endfor %}
        </ul>
        <a href="{% url 'tasks:add' %}">add a new task </a>
{% endblock %}

Django/secondProject/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>